name: Manual workflow

on: workflow_dispatch
  
jobs:
  setup:
    runs-on: ubuntu-latest
    name: Initial setup
    steps:
      - name: Action steps
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.PRIVATE_KEY}}
          script: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            git clone https://github.com/kuvvat/deploy.git
            cd deploy           
            mkdir -p ./Deployment/nginx/ssl
            sudo apt install certbot -y
            sudo certbot certonly --standalone --non-interactive --agree-tos --register-unsafely-without-email --preferred-challenges http --http-01-port 80 -d azirar.com -d www.azirar.com --dry-run
            cd Deployment
            sudo docker-compose up -d database
            sudo docker-compose up -d coreapi
            sudo docker-compose up -d web
            sudo cp -r ./renewal-hooks /etc/letsencrypt/
