name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy on AWS ec2 instance
    - uses: actions/checkout@v2
    with:
      host: ${{secrets.HOST}}
      username: ${{secrets.USERNAME}}
      key: ${{secrets.PRIVATE_KEY}}
      script: |
        docker stop sdk
        docker rm sdk
        cd /home/ubuntu/netcore
        docker-compose build coreapi
        docker-compose up -d coreapi
    
