name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy on Linux instance
    steps:
      - name: Action steps
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.PRIVATE_KEY}}
          script: |
            sudo docker stop sdk
            sudo docker rm sdk
            cd ./deploy/Deployment/
            sudo docker-compose build coreapi
            sudo docker-compose up -d coreapi
