name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy on AWS ec2 instance
    steps:
      - name: Action steps
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.PRIVATE_KEY}}
          script: |
            docker stop sdk
            docker rm sdk
            cd ./deploy/Deployment
            docker-compose build coreapi
            docker-compose up -d coreapi
